# Generated by Django 4.2.5 on 2023-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_producto_resenia"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
